learning_users/basic_app/urls.py
from django.urls import path, include
from basic_app import views

# template urls
app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',  include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    # path('', , ''),
]

learning_users/basic_app/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True)
    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from socket import fromshare
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_picture')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# imports
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, "basic_app/index.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if(request.method == 'POST'):
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if(user_form.is_valid() and profile_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if('profile_picture' in request.FILES):
                profile.profile_picture = request.FILES['profile_picture']

            profile.save()

            registered = True
        
        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, "basic_app/register.html", {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if(request.method == 'POST'):
        u_username = request.POST.get('username')
        u_password = request.POST.get('password')

        user = authenticate(username=u_username, password=u_password)

        if(user):
            if(user.is_active):
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("The account is not active!")
        else:
            print("Failed login attempt for " + u_username + " with " + u_password)
            return HttpResponse("Invalid login details!")
    else:
        return render(request, "basic_app/login.html")

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- <title>Base</title> -->
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Django App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}                
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        </div>
    </nav>

      <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>

</body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Django level 5</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please log in</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter your username">
        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

learning_users/templates/basic_app/register.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h2>Register here</h2>
        <h3>Fill out the form</h3>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}